### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by farski** [tphakala/birdnet-pi2go#1]
First, thanks for building this.

I tried to run it and ran into a couple issues. One is that the [copy operation](https://github.com/tphakala/birdnet-pi2go/blob/main/main.go#L77) gives a "required for move operation" error, which confused me for a couple minutes.

It also looks like there's a `merge` operation, which is actually the one I would have wanted, but it's not currently documented.

When only using the documented copy or move operations, it seems like `source-dir` is required for both, even when using `skip-audio-transfer true`. I wasn't quite sure how to handle that. It seems to give that error even if I do create and pass in some dummy directories for source and target.

Right now I have BirdNET-Pi and BirdNET-Go running on separate computers, and I'm actually trying to merge the DBs on a third computer, which I'm sure isn't how this was intended to be used, so I will try something a little simpler and see how it goes.

**Comment by tphakala** [comment]
Yeah I need to improve documentation, and I have to confess that I didn't test skip-audio-transfer true option much at all so there might be some logic issues with that. But in your case migration is easiest to run in out BirdNET-Pi host, point target-db to non-existing file and birdnet-pi2go will create a new db for you, point source-dir to BirdNET-Pi BirdSongs dir and point target-dir to empty directory.

Once migrate tool has copied BirdNET-Pi entries in new birdnet.db file you can merge it with your existing BirdNET-Go db using merge option, use existing BirdNET-Go datatabase as source and migration tool created db as target. Please note that birdnet-pi2go created sqlite is in Write Ahead Log mode so there are few additional database files (birdnet.db-shm and .db-wal) you need to copy over to your birdnet-go host.

**Comment by farski** [comment]
Success! Thank you
